# Generated by Django 4.1.7 on 2023-03-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0004_student_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='amount',
            field=models.CharField(default='1000', max_length=50),
        ),
    ]
